apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/8665140f96f6b238a20e578dba7f9aef91ddac51/manifests/ha/install.yaml # v3.1.9
  - https://github.com/argoproj/argo-workflows/releases/download/v3.7.2/install.yaml
