apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/7ae7d2cc723f5408b080a31263e705198af08613/manifests/ha/install.yaml # v3.3.8
  - https://github.com/argoproj/argo-workflows/releases/download/v3.7.2/install.yaml
