apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sandbox
spec:
  replicas: 1
  template:
    spec:
      repository: int128/sandbox
      # https://hub.docker.com/r/summerwind/actions-runner-dind/tags
      image: summerwind/actions-runner-dind:v2.277.1-ubuntu-20.04-f2680b2 # renovate
      dockerdWithinRunnerContainer: true
      resources:
        limits:
          memory: 512Mi
        requests:
          memory: 512Mi
