name: add-issue-to-project-on-assigned

# This will add an issue to the specific project.
#
# To get a project column id:
# https://docs.github.com/en/graphql/overview/explorer
#
# query {
#   repository(owner: "int128", name: "sandbox") {
#     project(number: 1) {
#       columns(first: 1) {
#         nodes {
#           name
#           id
#         }
#       }
#     }
#   }
# }

on:
  issues:
    types:
      - opened
      - assigned

jobs:
  int128:
    if: contains(github.event.issue.assignees.*.login, 'int128')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const mutation = `mutation($projectColumnId: ID!, $issueID: ID!) {
              addProjectCard(input: {projectColumnId: $projectColumnId, contentId: $issueID}) {
                projectColumn {
                  name
                }
              }
            }`
            const variables = {
              projectColumnId: 'MDEzOlByb2plY3RDb2x1bW4xMjk3MjU0OQ==', // https://github.com/int128/sandbox/projects/1
              issueID: context.payload.issue.node_id,
            }
            await github.graphql(mutation, variables)
