name: bot

on:
  issue_comment:
    types:
      - created

jobs:
  merge:
    if: github.event.issue.pull_request && github.event.comment.body == '/merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: pull
        with:
          script: |
            const { data: pull } = await github.rest.pulls.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              pull_number: context.issue.number,
            })
            console.info(`Updating base ${pull.base.ref} to head ${pull.head.sha}`)
            await github.rest.git.updateRef({
              owner: context.issue.owner,
              repo: context.issue.repo,
              ref: `heads/${pull.base.ref}`,
              sha: pull.head.sha,
            })
