name: bot

on:
  pull_request_review:
    types:
      - submitted

jobs:
  notice:
    if: |
      github.event.review.state == 'APPROVED' &&
      github.event.review.body != '/merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const { base, head } = context.payload.pull_request
            await github.rest.checks.create({
              ...context.repo,
              name: 'fast-forward-merge-bot',
              head_sha: head.sha,
              conclusion: 'failure',
              output: {
                title: 'Require review comment `/merge`',
                summary: 'To merge this pull request, approve it with a comment `/merge`',
              },
            })

  merge:
    if: |
      github.event.review.state == 'APPROVED' &&
      github.event.review.body == '/merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const { base, head } = context.payload.pull_request
            await github.rest.checks.create({
              ...context.repo,
              name: 'fast-forward-merge-bot',
              head_sha: head.sha,
              conclusion: 'success',
            })
      - uses: actions/github-script@v5
        with:
          script: |
            const { base, head } = context.payload.pull_request
            await github.rest.git.updateRef({
              ...context.repo,
              ref: `heads/${base.ref}`,
              sha: head.sha,
            })
      - if: failure()
        uses: actions/github-script@v5
        with:
          script: |
            const { base, head } = context.payload.pull_request
            await github.rest.checks.create({
              ...context.repo,
              name: 'fast-forward-merge-bot',
              head_sha: head.sha,
              conclusion: 'failure',
            })
