name: bot

on:
  issue_comment:
    types:
      - created

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: console.log(context.issue)

  merge:
    if: github.event.issue.pull_request && github.event.issue.body == '/merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: pull
        with:
          script: |
            return github.rest.pulls.get(context.issue)
      - uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.pull.outputs.result).data.head.ref }}
      - run: git push origin HEAD:$BASE_REF
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BASE_REF: refs/heads/${{ fromJSON(steps.pull.outputs.result).data.base.ref }}
