name: bot

on:
  issue_comment:
    types:
      - created
  pull_request_review:
    types:
      - submitted

jobs:
  approve:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/approve' &&
      github.actor == 'int128'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const { data: pull } = await github.rest.pulls.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              pull_number: context.issue.number,
            })
            await github.rest.checks.create({
              owner: context.issue.owner,
              repo: context.issue.repo,
              name: 'merge-bot',
              head_sha: pull.head.sha,
              conclusion: 'success',
              output: {
                title: `Ready to merge`,
                summary: `Ready to merge`,
              },
            })
            await github.rest.pulls.createReview({
              owner: context.issue.owner,
              repo: context.issue.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
            })

  fast-forward-merge-bot:
    if: |
      github.event_name == 'pull_request_review' &&
      github.event.review.body == '/merge'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const { base, head } = context.payload.pull_request
            await github.rest.checks.create({
              ...context.repo,
              name: 'fast-forward-merge-bot',
              head_sha: head.sha,
              status: 'completed',
              conclusion: 'success',
            })
            core.info(`Updating ${base.ref} to ${head.ref}@${head.sha}`)
            await github.rest.git.updateRef({
              ...context.repo,
              ref: `heads/${base.ref}`,
              sha: head.sha,
            })
