name: build

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/helloworld--build.yaml
      - helloworld/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/helloworld--build.yaml
      - helloworld/**
    tags:
      - helloworld/v*
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/helloworld
          # map git tag to docker tag
          # e.g. helloworld/v1.0.0 -> v1.0.0
          # https://github.com/docker/metadata-action#typematch
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=.+-(v.+),group=1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
      - id: build
        uses: docker/build-push-action@v2
        with:
          context: helloworld
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/helloworld:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/helloworld:cache,mode=max

      - run: docker run --rm ghcr.io/${{ github.repository }}/helloworld@${{ steps.build.outputs.digest }} cat /etc/os-release
      - run: docker run --rm ghcr.io/${{ github.repository }}/helloworld@${{ steps.build.outputs.digest }} cat /etc/os-release.build

  kaniko:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/helloworld/kaniko
          # map git tag to docker tag
          # e.g. helloworld/v1.0.0 -> v1.0.0
          # https://github.com/docker/metadata-action#typematch
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=.+-(v.+),group=1
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build
        uses: int128/kaniko-action@v1
        with:
          context: helloworld
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          verbosity: debug

      - run: docker run --rm ghcr.io/${{ github.repository }}/helloworld/kaniko@${{ steps.build.outputs.digest }} cat /etc/os-release
      - run: docker run --rm ghcr.io/${{ github.repository }}/helloworld/kaniko@${{ steps.build.outputs.digest }} cat /etc/os-release.build
