name: deployment

on:
  pull_request:
    branches: master

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('./.github/scripts/deployment.js')
            await script({ github, context, core })
