name: dump-workflow-run

on:
  workflow_call:
  workflow_run:
    workflows:
      - '*'
      - '!add-*'
    types:
      - completed

jobs:
  dump:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo "${{ github.event.workflow.name }}"
      - run: echo "${{ github.event.workflow_run.conclusion }}"
      - run: echo "${{ github.event.workflow_run.head_branch }}"
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            core.info(JSON.stringify(context.payload, undefined, 2))

  test-condition:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'master'
    steps:
      - run: echo
