name: dump-workflow-run

on:
  workflow_call:

jobs:
  dump:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: echo "${{ github.event.workflow.name }}"
      - run: echo "${{ github.event.workflow_run.conclusion }}"
      - run: echo "${{ github.event.workflow_run.head_branch }}"
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload, undefined, 2))
