name: helloworld

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/helloworld.yaml
      - helloworld/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/helloworld.yaml
      - helloworld/**
    tags:
      - helloworld/v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/helloworld
          # map git tag to docker tag
          # e.g. helloworld/v1.0.0 -> v1.0.0
          # https://github.com/docker/metadata-action#typematch
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=.+-(v.+),group=1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/GoogleContainerTools/kaniko#running-kaniko-in-docker
      - run: |
          docker run \
            -v $(pwd):/workspace \
            -v ~/.docker/config.json:/kaniko/.docker/config.json:ro \
            gcr.io/kaniko-project/executor:latest \
            --dockerfile /workspace/Dockerfile \
            --destination "${{ steps.metadata.outputs.tags }}" \
            --context dir:///workspace/ \
            --cache=true

#       - uses: docker/build-push-action@v2
#         with:
#           context: helloworld
#           push: true
#           tags: ${{ steps.metadata.outputs.tags }}
#           labels: ${{ steps.metadata.outputs.labels }}
#           cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/helloworld:cache
#           cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/helloworld:cache,mode=max
