name: investigate

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}
      - run: echo ${{ github.event.pull_request.number }}
