name: '[manual] Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: choice
        required: true
        options:
          - staging
          - production

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: config
        with:
          script: |
            core.info(JSON.stringify(context.payload, undefined, 2))

      - uses: int128/release-note-action@v0
        id: release-note
        with:
          base: refs/heads/${{ github.event.inputs.environment }}
          head: refs/heads/master

      - uses: actions/github-script@v6
        env:
          body: ${{ steps.release-note.outputs.pull-request-list-markdown }}
        with:
          script: |
            const { data: pull } = await github.rest.pulls.create({
              ...context.repo,
              base: context.payload.inputs.environment,
              head: 'master',
              title: `Deploy to ${context.payload.inputs.environment}`,
              body: process.env.body,
            })
            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: pull.number,
              reviewers: [context.actor],
            })
            await octokit.rest.issues.addAssignees({
              ...context.repo,
              issue_number: pull.number,
              assignees: [context.actor],
            })
