name: '[manual] Deploy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: choice
        required: true
        options:
          - staging
          - production

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: config
        with:
          script: |
            core.setOutput('base', context.payload.inputs.environment)
            core.setOutput('head', 'master')

      - uses: int128/release-note-action@v0
        id: release-note
        with:
          base: refs/heads/${{ steps.config.outputs.base }}
          head: refs/heads/${{ steps.config.outputs.head }}

      - uses: actions/github-script@v6
        env:
          base: ${{ steps.config.outputs.base }}
          head: ${{ steps.config.outputs.head }}
          body: |
            ## Release note
            ${{ steps.release-note.outputs.body }}
        with:
          script: |
            const { data: pull } = await github.rest.pulls.create({
              ...context.repo,
              base: process.env.base,
              head: process.env.head,
              title: `Deploy to ${context.payload.inputs.environment}`,
              body: process.env.body,
            })
            await github.rest.pulls.requestReviewers({
              ...context.repo,
              pull_number: pull.number,
              reviewers: [context.actor],
            })
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: pull.number,
              assignees: [context.actor],
            })
