name: '[manual] Deploy'

on:
  workflow_dispatch:
    inputs:
      service:
        description: Service to deploy
        required: true
        options:
          - frontend
          - backend
      environment:
        description: Environment to deploy
        required: true
        options:
          - staging
          - production

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: config
        with:
          script: |
            core.info(JSON.stringify(context.payload, undefined, 2))
