name: nested-workflow

on:
  pull_request:

jobs:
  dump:
    strategy:
      matrix:
        target:
          - dump-workflow-run
    uses: ./.github/workflows/${{ matrix.target }}.yaml
    with:
      target: ${{ matrix.target }}
