name: notify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: exit 1
      - if: always()
        uses: quipper/slack-notification-action@v2
        with:
          slack-channel-id: TEST
