name: notify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  slack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: quipper/slack-notification-action@v2
        with:
          slack-channel-id: TEST
