name: pull-request-hook

on:
  pull_request:
    branches: [ master ]

jobs:
  show-number:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/github-script
      - uses: actions/github-script@v4
        id: list-open-pulls
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // https://octokit.github.io/rest.js/v18#pulls-list
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
            })
            return pulls.map((pull) => `pr-${pull.number}`)
      - run: |
          cat <<EOF
          ${{ steps.list-open-pulls.outputs.result }}
          EOF

      - uses: actions/github-script@v4
        id: list-labeled-pulls
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = await github.graphql(`
              query($owner:String!, $name:String!, $labels:[String!]) {
                repository(owner: $owner, name: $name) {
                  pullRequests(states: OPEN, labels: $labels, first: 10) {
                    nodes {
                      number
                    }
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              name: context.repo.repo,
              labels: ['Deploy']
            })
            console.log(result)
            return result.data.repository.pullRequests.nodes.map((node) => `pr-${node.number}`)

      - run: |
          cat <<EOF
          ${{ steps.list-labeled-pulls.outputs.result }}
          EOF
