name: pull-request-hook

on:
  pull_request:
    branches: [ master ]

jobs:
  show-number:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/github-script
      - uses: actions/github-script@v4
        id: list-open-pulls
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // https://octokit.github.io/rest.js/v18#pulls-list
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
            })
            return pulls.map((pull) => pull.number)
      - run: echo ${{ steps.list-open-pulls.result }}
