name: pull-request-unlabeled

on:
  pull_request:
    types:
      - unlabeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.event.pull_request }}" | jq .
      - run: git rev-parse HEAD
