name: pull-request-label

on:
  pull_request:
    types:
      - labeled

jobs:
  example:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: echo '${{ github.ref }}'
