name: release

on:
  workflow_dispatch:
    inputs:
      base:
        type: choice
        description: base branch
        options: 
          - production

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gh pr create --base ${{ github.event.inputs.base }} --head master --title Release --body Release --draft
        env:
          GITHUB_TOKEN: ${{ github.token }}
