name: ruby

on:
  pull_request:

jobs:
  run:
    container:
      image: ruby:3.1
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ruby -v
