name: sandbox

on:
  pull_request:
    paths:
      - .github/workflows/sandbox.yaml

jobs:
  do:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            await octokit.rest.repos.deleteAnEnvironment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment_name: 'pr-226',
            })
