name: status

on:
  pull_request:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.checks.create({
              ...context.repo,
              name: 'status-demo',
              head_sha: context.payload.pull_request.head.sha,
              output: {
                title: 'Require comment `/merge` to merge',
                summary: 'To merge, post a comment `/merge` to the pull request',
              },
            })
