name: update-generated-files-action

on:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: date > timestamp
      - uses: int128/update-generated-files-action@v2
