on:
  workflow_jobs: {}

jobs:
  submit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: env
      - run: |
          cat <<EOF
          ${{ toJSON(github.event.workflow_jobs) }}
          EOF
